# Site
name: "PHCarrer"
title: "PHCarrer"
description: "We've helped million+ people grow their careers. These articles share tips on resumes, the job search, and more"
logo: 'assets/images/logo.png'
favicon: 'assets/images/icon.png'
baseurl: ''
url: 
google_analytics: 'G-6XCXLHK0WG'
disqus: ''
mailchimp-list: 'https://club.us5.list-manage.com/subscribe/post?u=a839bbbdc37891b132e7db91c&amp;id=d151dabdf3'
include: ["_pages"]
permalink: /:title/
email: 
formsfree: 

# Authors
authors:

  PhCareer:
    name: PhCareer
    display_name: PhCareer    
    avatar: 'assets/images/avatar.jpg'
    email: phcareer@gmail.com
    gravatar: 
    web: 
    facebook: https://facebook.com/rubbiesvlog
    description: "share tips on resumes, the job search, and more"


    

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-admin
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"




# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
