# Site
name: "Zooted"
title: "Zooted"
description: "We've helped thousand+ people grow their careers. These articles share tips on resumes, the job search, and more"
logo: 'assets/images/logo.png'
favicon: 'assets/images/icon.png'
baseurl: ''
url: 'https://www.zooted.me'
google_analytics: 'G-6XCXLHK0WG'
disqus: 'zooted'
mailchimp-list: 'https://club.us5.list-manage.com/subscribe/post?u=a839bbbdc37891b132e7db91c&amp;id=d151dabdf3'
include: ["_pages"]
permalink: /:title/
email: 
formsfree: 

# Authors
authors:

  PhCareer:
    name: Zooted
    display_name: Zooted    
    avatar: 'assets/images/avatar.jpg'
    email: Zooted.me@gmail.com
    gravatar: 
    web: 
    facebook: https://facebook.com/Zooted
    description: "Share tips on resumes, the job search, and more"


 
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-admin
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"


# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]


collections:
      - Work From Home
      - Job Search
      - Job Hiring
      - Resume Guide
      - Engineering
      - Accounting
      - Arts
      - Administrative
      - Advertising
      - Automotive
      - Banking
      - Biotech
      - Computer
      - Construction
      - Criminal Justice
      - Counselling
      - Design
      - Education
      - Engineering
      - Electrical Engineering
      - Entertainment
      - Entry Level
      - Executive
      - Finance
      - Franchise
      - Federal
      - Forensic Science
      - General Labor
      - Graphic Designer
      - Government
      - Healthcare
      - HVAC
      - Human Resources
      - Information Technology
      - Insurance
      - Inventory
      - Journalism
      - Law Enforcement
      - Legal
      - Management Consulting
      - Manufacturing
      - Marketing
      - Medical Assistant
      - Medical Transcription
      - Music Industry
      - NHS
      - Nurse
      - Online Teaching
      - Pharmaceutical
      - Paralegal
      - Plumbing
      - Project manager
      - Publishing
      - Psychology
      - Real Estate
      - Renewable Energy
      - Research
      - Restaurant
      - Retail
      - Sales
      - Science
      - Skilled Labor Trades
      - Software Testing
      - Sports Management
      - Strategy Planning
      - Supply Chain
      - Telecommunications
      - Training
      - Travel
      - Travelling
      - Trucking
      - Truck Driver
      - Veterinary
      - Warehouse
      - Web Design

      

      