# config.yml

backend:
  name: git-gateway
  # repo: ruubbies-vlog/ruubbies-vlog.github.io
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured", name: "image", widget: "image" }
      - { label: "Slug", name: "permalink", widget: "string" }
      - { label: "Category", name: "categories", widget: "select", multiple: true , options: ["Work From Home", "Hybrid Workplace", "Part-Time Jobs", "Work-Life Balance", "Job Search", "Job Hiring", "Job Interview",  "Job Intervies", "Soft Skills", "Hard Skills", "Resume Guide", "Engineering", "Accounting", "Arts", "Administrative", "Freelance Jobs", "Good Communications",  "Advertising", "Automotive", "Banking", "Biotech", "Computer", "Construction", "Criminal Justice", "Counselling", "Design", "Education", "Engineering", "Electrical Engineering", "Entertainment", "Entry Level", "Executive", "Finance", "Franchise", "Federal", "Forensic Science", "General Labor", "Graphic Designer", "Government", "Healthcare", "HVAC", "Human Resources", "Information Technology", "Insurance", "Inventory", "Career Guide", "Journalism", "Law Enforcement", "Legal", "Management Consulting", "Manufacturing", "Marketing", "Medical Assistant", "Medical Transcription", "Music Industry", "NHS", "Nurse", "Online Teaching", "Pharmaceutical", "Paralegal", "Plumbing", "Project manager", "Publishing", "Psychology", "Real Estate", "Renewable Energy", "Research", "Restaurant", "Retail", "Sales", "Science", "Skilled Labor Trades", "Software Testing", "Sports Management", "Strategy Planning", "Supply Chain", "Telecommunications", "Training", "Travel", "Travelling", "Trucking", "Truck Driver", "Veterinary", "Warehouse", "Web Design"] }
      - { label: "TOC", name: "toc", widget: "boolean", default: true }
      - { label: "Comments", name: "comments", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string", default: Zooted }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      